# -*- coding: utf-8 -*-
"""512 vit_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10asRpDEdepjybQZ8CTWOT-eyLWHGLmOA
"""

!pip install segment-anything
import numpy as np
import torch
import rasterio
import cv2
import geopandas as gpd
from shapely.geometry import Polygon
from rasterio.windows import Window
import gc

from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

# PATHS
IMAGE_PATH = r"/content/drive/MyDrive/GUJ_235182318471_3_JAN_2021_C2EM.tif"
SAM_CHECKPOINT = r"/content/drive/MyDrive/sam_vit_b_01ec64.pth"
OUTPUT_FILE = r"/content/sam_output.shp"

# 🔥 OPTIMIZED SETTINGS
TILE_SIZE = 512
STRIDE = 384   # overlap (important)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# LOAD MODEL
sam = sam_model_registry["vit_b"](checkpoint=SAM_CHECKPOINT)
sam.to(device)

mask_generator = SamAutomaticMaskGenerator(
    sam,
    points_per_side=7,         # 🔥 balanced
    points_per_batch=32,       # safe for GPU
    pred_iou_thresh=0.86,
    stability_score_thresh=0.90,
    min_mask_region_area=80,   # detect small farms
    crop_n_layers=0
)

# 🔥 STORE ALL POLYGONS (FAST)
all_polygons = []

with rasterio.open(IMAGE_PATH) as src:

    width = src.width
    height = src.height
    transform = src.transform
    crs = src.crs

    print("Image size:", width, height)

    for y in range(0, height, STRIDE):
        for x in range(0, width, STRIDE):

            print(f"Tile: {x},{y}")

            win_w = min(TILE_SIZE, width - x)
            win_h = min(TILE_SIZE, height - y)

            window = Window(x, y, win_w, win_h)
            image = src.read(window=window)

            # HANDLE BANDS
            if image.shape[0] == 1:
                image = np.repeat(image, 3, axis=0)
            else:
                image = image[:3]

            image = image.astype(np.float32)

            for i in range(3):
                band = image[i]
                if band.max() > band.min():
                    band = (band - band.min()) / (band.max() - band.min())
                image[i] = band * 255

            image = image.astype(np.uint8)
            image = np.transpose(image, (1, 2, 0))

            # PAD
            padded = np.zeros((TILE_SIZE, TILE_SIZE, 3), dtype=np.uint8)
            padded[:image.shape[0], :image.shape[1]] = image

            try:
                with torch.no_grad():
                    masks = mask_generator.generate(padded)

            except RuntimeError as e:
                print("Skipping tile:", e)
                torch.cuda.empty_cache()
                continue

            # MASK → POLYGON
            for m in masks:

                mask = m["segmentation"].astype(np.uint8)
                mask = mask[:image.shape[0], :image.shape[1]]

                contours, _ = cv2.findContours(
                    mask,
                    cv2.RETR_EXTERNAL,
                    cv2.CHAIN_APPROX_SIMPLE
                )

                for cnt in contours:

                    if len(cnt) < 4:
                        continue

                    coords = []

                    for pt in cnt:
                        px = pt[0][0] + x
                        py = pt[0][1] + y

                        gx, gy = rasterio.transform.xy(transform, py, px)
                        coords.append((gx, gy))

                    poly = Polygon(coords)

                    if poly.is_valid:
                        all_polygons.append(poly)

            # CLEAN MEMORY
            del masks
            torch.cuda.empty_cache()
            gc.collect()

# 🔥 SAVE ONCE (VERY FAST)
print("Saving final shapefile...")

gdf = gpd.GeoDataFrame(geometry=all_polygons, crs=crs)
gdf.to_file(OUTPUT_FILE)

print("Done ✅")

from google.colab import drive
drive.mount('/content/drive')